"use client"

import { useState, useTransition } from "react"
import { useRouter } from "@/navigation"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Input } from "@/components/ui/input"
import { attachLegalDraftToReleaseAction, createLegalAcceptanceDraftAction, updateLegalAcceptanceDraftAction, validateLegalAcceptanceDraftAction } from "@/app/actions/legal-configuration"
import type { LegalAdministrationPageData } from "@/lib/legal/admin-types"

export function LegalAcceptanceConfigurationForm({ data, canEdit, canValidate, canAttach }: { data: LegalAdministrationPageData; canEdit: boolean; canValidate: boolean; canAttach: boolean }) {
  const router = useRouter(); const draft = data.draftAcceptance; const [config, setConfig] = useState(draft?.configuration); const [summary, setSummary] = useState(draft?.changeSummary ?? "Legal acceptance update"); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition()
  const run = <T extends { error: string } | { success: true }>(task: () => Promise<T>, success: string) => startTransition(async () => { const result = await task(); const error = "error" in result ? result.error : undefined; setMessage(error ?? success); if (!error) router.refresh() })
  if (!draft || !config) return <section className="rounded-xl border bg-background p-5"><h2 className="font-semibold">Legal Acceptance configuration</h2><p className="mt-1 text-sm text-muted-foreground">Create a policy draft only after both required document types are published.</p>{canEdit ? <Button className="mt-4" onClick={() => run(() => createLegalAcceptanceDraftAction({ source: data.liveAcceptance ? "LIVE" : "DEFAULT" }), "Policy draft created.")} disabled={pending}>Create {data.liveAcceptance ? "from live" : "legal policy draft"}</Button> : <p className="mt-3 text-sm">Read-only access</p>}{message ? <p className="mt-3 text-sm">{message}</p> : null}</section>
  const published = data.documents.filter(({ status }) => status === "PUBLISHED"); const set = <K extends keyof typeof config>(key: K, value: (typeof config)[K]) => setConfig((current) => current ? { ...current, [key]: value } : current)
  const updateLabels = (locale: string, field: string, value: string) => set("translations", config.translations.map((item) => item.locale === locale ? { ...item, [field]: value } : item))
  return <section className="space-y-5 rounded-xl border bg-background p-5"><div><h2 className="font-semibold">Legal Acceptance configuration</h2><p className="text-sm text-muted-foreground">Draft v{draft.versionNumber} · revision {draft.revision}. Activation remains on the Overview.</p></div><label className="flex gap-3 rounded-lg border p-3"><Checkbox checked={config.bookingEnforcementEnabled} onCheckedChange={(value) => set("bookingEnforcementEnabled", value === true)} disabled={!canEdit}/><span><span className="font-medium">Require configured legal behavior during booking</span><span className="block text-sm text-muted-foreground">Off preserves Phase 1–6 checkout and creates no acceptance evidence.</span></span></label>
    <div className="grid gap-4 sm:grid-cols-2"><DocumentControl label="Rental Terms" type="RENTAL_TERMS" documents={published} documentId={config.termsDocument.id} mode={config.termsAcceptance} presentation={config.termsPresentation} disabled={!canEdit} onDocument={(id) => { const document = published.find((item) => item.id === id)!; set("termsDocument", { id: document.id, type: "RENTAL_TERMS", publicationStatus: "PUBLISHED", availableLocales: document.translations.map(({ locale }) => locale), contentHash: document.manifestHash ?? "" }) }} onMode={(value) => set("termsAcceptance", value)} onPresentation={(value) => set("termsPresentation", value)}/><DocumentControl label="Privacy Notice acknowledgement" type="PRIVACY_NOTICE" documents={published} documentId={config.privacyDocument.id} mode={config.privacyAcknowledgment} presentation={config.privacyPresentation} disabled={!canEdit} onDocument={(id) => { const document = published.find((item) => item.id === id)!; set("privacyDocument", { id: document.id, type: "PRIVACY_NOTICE", publicationStatus: "PUBLISHED", availableLocales: document.translations.map(({ locale }) => locale), contentHash: document.manifestHash ?? "" }) }} onMode={(value) => set("privacyAcknowledgment", value)} onPresentation={(value) => set("privacyPresentation", value)}/></div>
    <div><h3 className="font-medium">Required booking languages</h3><div className="mt-2 flex flex-wrap gap-3">{data.supportedLocales.map((locale) => <label key={locale} className="flex gap-2 rounded border p-2 text-sm"><Checkbox checked={config.requiredLocales.includes(locale)} onCheckedChange={(value) => { const requiredLocales = value === true ? [...config.requiredLocales, locale] : config.requiredLocales.filter((item) => item !== locale); let translations = config.translations; if (value === true && !translations.some((item) => item.locale === locale)) translations = [...translations, { locale, termsCheckboxLabel: "I acknowledge the Rental Terms.", termsLinkLabel: "Rental Terms", privacyCheckboxLabel: "I acknowledge that I have read the Privacy Notice.", privacyLinkLabel: "Privacy Notice" }]; setConfig({ ...config, requiredLocales, translations }) }} disabled={!canEdit}/>{locale}</label>)}</div></div>
    {config.requiredLocales.map((locale) => { const labels = config.translations.find((item) => item.locale === locale); if (!labels) return null; return <div key={locale} className="rounded-lg border p-4"><h3 className="font-medium">Customer labels · {locale}</h3><div className="mt-3 grid gap-3 sm:grid-cols-2"><Input value={labels.termsLinkLabel} onChange={(event) => updateLabels(locale, "termsLinkLabel", event.target.value)} disabled={!canEdit} placeholder="Rental Terms link label"/><Input value={labels.termsCheckboxLabel ?? ""} onChange={(event) => updateLabels(locale, "termsCheckboxLabel", event.target.value)} disabled={!canEdit} placeholder="Rental Terms acknowledgement"/><Input value={labels.privacyLinkLabel} onChange={(event) => updateLabels(locale, "privacyLinkLabel", event.target.value)} disabled={!canEdit} placeholder="Privacy Notice link label"/><Input value={labels.privacyCheckboxLabel ?? ""} onChange={(event) => updateLabels(locale, "privacyCheckboxLabel", event.target.value)} disabled={!canEdit} placeholder="Privacy Notice acknowledgement"/></div></div> })}
    <label className="flex gap-2 text-sm"><Checkbox checked={config.retainRenderedSnapshot} onCheckedChange={(value) => set("retainRenderedSnapshot", value === true)} disabled={!canEdit}/>Retain exact canonical legal text with acceptance evidence</label><label className="flex gap-2 text-sm"><Checkbox checked={config.showInConfirmation} onCheckedChange={(value) => set("showInConfirmation", value === true)} disabled={!canEdit}/>Show accepted version references in confirmations</label><Input value={summary} onChange={(event) => setSummary(event.target.value)} disabled={!canEdit}/>
    <div className="flex flex-wrap gap-2">{canEdit ? <Button onClick={() => run(() => updateLegalAcceptanceDraftAction({ versionId: draft.id, expectedRevision: draft.revision, changeSummary: summary, configuration: config }), "Legal policy saved." )} disabled={pending}>Save policy draft</Button> : null}{canValidate ? <Button variant="outline" onClick={() => run(() => validateLegalAcceptanceDraftAction(), "Policy validation completed." )} disabled={pending}>Validate policy</Button> : null}{canAttach ? <Button variant="outline" onClick={() => run(() => attachLegalDraftToReleaseAction({ versionId: draft.id }), "Policy attached to release draft." )} disabled={pending}>Attach exact policy to release</Button> : null}</div>{message ? <p className="rounded bg-muted p-2 text-sm">{message}</p> : null}</section>
}

function DocumentControl({ label, type, documents, documentId, mode, presentation, disabled, onDocument, onMode, onPresentation }: { label: string; type: string; documents: LegalAdministrationPageData["documents"]; documentId: string; mode: "REQUIRED" | "DISPLAY_ONLY" | "DISABLED"; presentation: "INLINE" | "DIALOG"; disabled: boolean; onDocument: (id: string) => void; onMode: (value: "REQUIRED" | "DISPLAY_ONLY" | "DISABLED") => void; onPresentation: (value: "INLINE" | "DIALOG") => void }) { return <div className="space-y-3 rounded-lg border p-4"><h3 className="font-medium">{label}</h3><select className="w-full rounded border p-2" value={documentId} onChange={(event) => onDocument(event.target.value)} disabled={disabled}>{documents.filter((item) => item.type === type).map((item) => <option key={item.id} value={item.id}>Version {item.versionNumber} · {item.translations.map(({ locale }) => locale).join(", ")}</option>)}</select><select className="w-full rounded border p-2" value={mode} onChange={(event) => onMode(event.target.value as typeof mode)} disabled={disabled}><option value="REQUIRED">Required — explicit unchecked acknowledgement</option><option value="DISPLAY_ONLY">Display only — no acceptance evidence</option><option value="DISABLED">Disabled</option></select><select className="w-full rounded border p-2" value={presentation} onChange={(event) => onPresentation(event.target.value as typeof presentation)} disabled={disabled}><option value="DIALOG">Open exact version in a dialog/page</option><option value="INLINE">Show exact version inline</option></select></div> }
