"use client"

import { useState, useTransition } from "react"
import { useRouter } from "@/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { LegalContent } from "./legal-content"
import { archiveLegalVersionAction, createLegalDraftAction, discardLegalDraftAction, publishLegalVersionAction, updateLegalDraftAction, validateLegalDraftAction } from "@/app/actions/legal-configuration"
import type { LegalAdministrationPageData, LegalAdminDocument } from "@/lib/legal/admin-types"

const label = (type: string) => type === "RENTAL_TERMS" ? "Rental Terms" : "Privacy Notice"

export function LegalDocumentList({ data, canEdit, canPublish, canValidate }: { data: LegalAdministrationPageData; canEdit: boolean; canPublish: boolean; canValidate: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState<string>(); const [pending, startTransition] = useTransition()
  const run = <T extends { error: string } | { success: true }>(task: () => Promise<T>, success: string) => startTransition(async () => { const result = await task(); const error = "error" in result ? result.error : undefined; setMessage(error ?? success); if (!error) router.refresh() })
  return <div className="space-y-5">
    <section className="rounded-xl border bg-amber-50 p-4 text-sm text-amber-950"><strong>Legal review required.</strong> Legal text should be reviewed by a qualified legal professional before publication.</section>
    {(["RENTAL_TERMS", "PRIVACY_NOTICE"] as const).map((type) => {
      const items = data.documents.filter((document) => document.type === type); const draft = items.find(({ status }) => status === "DRAFT"); const latest = items.find(({ status }) => status === "PUBLISHED")
      return <section key={type} className="rounded-xl border bg-background p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{label(type)}</h2><p className="text-sm text-muted-foreground">{latest ? `Published v${latest.versionNumber} · ${latest.translations.map(({ locale }) => locale).join(", ")}` : "No published version"}</p></div>{!draft && canEdit ? <Button onClick={() => run(() => createLegalDraftAction({ type, primaryLocale: data.supportedLocales[0], changeSummary: `Update ${label(type)}`, sourceDocumentId: latest?.id }), "Draft created.")} disabled={pending}>Create {latest ? "from published" : "initial draft"}</Button> : null}</div>
      {draft ? <LegalDraftEditor document={draft} supportedLocales={data.supportedLocales} canEdit={canEdit} canPublish={canPublish} canValidate={canValidate} run={run} pending={pending}/> : null}
      {items.filter(({ status }) => status !== "DRAFT").length ? <div className="mt-5 border-t pt-4"><h3 className="font-medium">Publication history</h3><div className="mt-2 space-y-2">{items.filter(({ status }) => status !== "DRAFT").map((document) => <div key={document.id} className="flex flex-wrap items-center justify-between gap-2 rounded border p-3 text-sm"><span>Version {document.versionNumber} · {document.status === "PUBLISHED" ? "Published" : "Archived"} · {document.publishedAt ? new Date(document.publishedAt).toLocaleString() : "legacy publication"} · used by {document.configurationUsage} policies</span>{document.status === "PUBLISHED" && canPublish ? <Button variant="outline" size="sm" onClick={() => { if (window.confirm("Archive this publication for future configuration? Historical bookings remain linked.")) run(() => archiveLegalVersionAction({ documentId: document.id }), "Publication archived.") }}>Archive</Button> : null}</div>)}</div></div> : null}
      </section>
    })}
    {message ? <p className="rounded border bg-muted p-3 text-sm">{message}</p> : null}
  </div>
}

function LegalDraftEditor({ document, supportedLocales, canEdit, canPublish, canValidate, run, pending }: { document: LegalAdminDocument; supportedLocales: string[]; canEdit: boolean; canPublish: boolean; canValidate: boolean; run: <T extends { error: string } | { success: true }>(task: () => Promise<T>, success: string) => void; pending: boolean }) {
  const [primaryLocale, setPrimaryLocale] = useState(document.primaryLocale ?? supportedLocales[0]); const [summary, setSummary] = useState(document.changeSummary); const [translations, setTranslations] = useState(document.translations.map(({ locale, title, canonicalContent }) => ({ locale, title, canonicalContent }))); const [previewLocale, setPreviewLocale] = useState(document.primaryLocale ?? supportedLocales[0])
  const current = translations.find(({ locale }) => locale === previewLocale) ?? translations[0]
  const update = (locale: string, field: "title" | "canonicalContent", value: string) => setTranslations((items) => items.map((item) => item.locale === locale ? { ...item, [field]: value } : item))
  return <div className="mt-5 space-y-4 border-t pt-5"><div className="flex flex-wrap gap-3 text-sm"><span className="rounded bg-muted px-2 py-1">Draft v{document.versionNumber}</span><span className="rounded bg-muted px-2 py-1">{document.validationStatus}</span><span className="text-muted-foreground">Revision {document.revision}</span></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Primary language<select className="mt-1 w-full rounded-md border p-2" value={primaryLocale} onChange={(event) => setPrimaryLocale(event.target.value)} disabled={!canEdit}>{supportedLocales.map((locale) => <option key={locale}>{locale}</option>)}</select></label><label className="text-sm font-medium">Change summary<Input className="mt-1" value={summary} onChange={(event) => setSummary(event.target.value)} disabled={!canEdit}/></label></div>
    <div className="flex flex-wrap gap-2">{supportedLocales.map((locale) => <Button key={locale} size="sm" variant={previewLocale === locale ? "default" : "outline"} onClick={() => { setPreviewLocale(locale); if (!translations.some((item) => item.locale === locale) && canEdit) setTranslations((items) => [...items, { locale, title: "", canonicalContent: "" }]) }}>{locale}{translations.some((item) => item.locale === locale) ? "" : " +"}</Button>)}</div>
    {current ? <div className="grid gap-5 lg:grid-cols-2"><div className="space-y-3"><label className="text-sm font-medium">Customer title<Input className="mt-1" value={current.title} onChange={(event) => update(current.locale, "title", event.target.value)} disabled={!canEdit}/></label><label className="block text-sm font-medium">Canonical plain text<textarea className="mt-1 min-h-80 w-full rounded-md border bg-background p-3 font-mono text-sm" value={current.canonicalContent} onChange={(event) => update(current.locale, "canonicalContent", event.target.value)} disabled={!canEdit}/></label><p className="text-xs text-muted-foreground">Plain text only. HTML, Markdown templates, scripts, event handlers, iframes, and executable links are rejected.</p></div><div className="rounded-lg border p-4"><div className="mb-4 rounded bg-amber-100 p-2 text-xs font-medium text-amber-950">Draft customer preview · {current.locale}</div><h3 className="mb-4 text-xl font-semibold">{current.title || "Untitled legal document"}</h3><LegalContent content={current.canonicalContent || "Preview appears here."}/><p className="mt-5 text-xs text-muted-foreground">Version {document.versionNumber} · Draft · acknowledgement remains unchecked</p></div></div> : null}
    <div className="flex flex-wrap gap-2">{canEdit ? <Button onClick={() => run(() => updateLegalDraftAction({ documentId: document.id, expectedRevision: document.revision, primaryLocale, changeSummary: summary, translations }), "Legal draft saved." )} disabled={pending}>Save draft</Button> : <span className="text-sm text-muted-foreground">Read-only access</span>}{canValidate ? <Button variant="outline" onClick={() => run(() => validateLegalDraftAction({ documentId: document.id, expectedRevision: document.revision }), "Validation completed." )} disabled={pending}>Validate</Button> : null}{canPublish ? <Button variant="outline" onClick={() => { if (window.confirm(`Publish ${label(document.type)} version ${document.versionNumber}? Published content and translations become immutable.`)) run(() => publishLegalVersionAction({ documentId: document.id, expectedRevision: document.revision, warningsAcknowledged: true }), "Legal version published." ) }} disabled={pending}>Publish this legal version</Button> : null}{canEdit ? <Button variant="destructive" onClick={() => { if (window.confirm("Discard this legal draft? Published versions are unaffected.")) run(() => discardLegalDraftAction({ documentId: document.id, expectedRevision: document.revision }), "Draft discarded." ) }} disabled={pending}>Discard draft</Button> : null}</div>
  </div>
}
