export const DOCUMENT_ERROR_CODES = [
  "DOCUMENT_SESSION_NOT_FOUND",
  "DOCUMENT_SESSION_EXPIRED",
  "DOCUMENT_SESSION_ABORTED",
  "DOCUMENT_SESSION_ALREADY_COMPLETED",
  "DOCUMENT_INTENT_NOT_FOUND",
  "DOCUMENT_INTENT_MISMATCH",
  "DOCUMENT_UPLOAD_NOT_FOUND",
  "DOCUMENT_UPLOAD_INCOMPLETE",
  "DOCUMENT_UPLOAD_METADATA_MISMATCH",
  "DOCUMENT_IDEMPOTENCY_CONFLICT",
  "DOCUMENT_FILE_EMPTY",
  "DOCUMENT_FILE_TOO_LARGE",
  "DOCUMENT_FILENAME_UNSAFE",
  "DOCUMENT_EXTENSION_UNSUPPORTED",
  "DOCUMENT_MIME_UNSUPPORTED",
  "DOCUMENT_SIGNATURE_INVALID",
  "DOCUMENT_MIME_MISMATCH",
  "DOCUMENT_EXTENSION_MISMATCH",
  "DOCUMENT_ACTIVE_CONTENT_REJECTED",
  "DOCUMENT_SCAN_NOT_CLEAN",
  "DOCUMENT_ACCESS_DENIED",
  "DOCUMENT_RECENT_AUTH_REQUIRED",
  "RECENT_AUTH_REQUIRED",
  "RECENT_AUTH_EXPIRED",
  "RECENT_AUTH_EVIDENCE_MISSING",
  "RECENT_AUTH_PROVIDER_UNAVAILABLE",
  "DOCUMENT_REVIEW_NOT_PENDING",
  "DOCUMENT_REVIEW_STALE_REVISION",
  "DOCUMENT_REVIEW_REASON_REQUIRED",
  "DOCUMENT_REVIEW_NOTE_INVALID",
  "DOCUMENT_REVIEW_QUEUE_UNAVAILABLE",
  "DOCUMENT_NOT_ACCESSIBLE",
  "DOCUMENT_LEGAL_HOLD_ACTIVE",
  "DOCUMENT_LEGAL_HOLD_REQUIRED_REASON",
  "DOCUMENT_DELETION_NOT_ELIGIBLE",
  "DOCUMENT_PROVIDER_OPERATION_FAILED",
  "DOCUMENT_PROVIDER_AUTH_UNAVAILABLE",
  "DOCUMENT_PROVIDER_STORE_UNAVAILABLE",
  "DOCUMENT_PROVIDER_STORE_MISMATCH",
  "DOCUMENT_PROVIDER_REGION_MISMATCH",
  "DOCUMENT_PROVIDER_THROTTLED",
  "DOCUMENT_PROVIDER_TIMEOUT",
  "DOCUMENT_PROVIDER_RESPONSE_INVALID",
  "DOCUMENT_PROVIDER_CAPABILITY_UNSUPPORTED",
  "DOCUMENT_PATHNAME_INVALID",
  "DOCUMENT_OBJECT_ALREADY_EXISTS",
  "DOCUMENT_RESPONSE_TOO_LARGE",
  "DOCUMENT_DELETION_NOT_VERIFIED",
  "DOCUMENT_RETRY_LIMIT_REACHED",
  "DOCUMENT_INVALID_PROVENANCE",
] as const;
export type DocumentErrorCode = (typeof DOCUMENT_ERROR_CODES)[number];

export class PrivateDocumentError extends Error {
  constructor(
    readonly code: DocumentErrorCode,
    message: string,
    readonly retryable = false,
  ) {
    super(message);
    this.name = "PrivateDocumentError";
  }
}
export function documentError(
  code: DocumentErrorCode,
  message: string,
  retryable = false,
): never {
  throw new PrivateDocumentError(code, message, retryable);
}
